# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y_2c44K4500WM3PlNvDqYqd8vMF8oWoo
"""

import pandas as pd
import matplotlib.pyplot as plt

filename = 'preprocess.py'

with open(filename, 'r', encoding='utf-8') as file:
    content = file.read()
df = pd.read_csv('melb_data.csv')
# Просмотр первых нескольких строк данных
print(df.head(10))

import seaborn as sns

sns.regplot(x='BuildingArea', y='Price', data=df)

plt.xlim(0, 800) #устанавливаем максимальное значение
plt.ylim(0, 8000000) #устанавливаем максимальное значение
plt.xlabel('Building Area (м. кв)')
plt.ylabel('Price (млн)')
plt.title('Зависимость стоимости от площади')
plt.show()

colors = ['darkred', 'green', 'violet']
sns.boxplot(x='Type', y='BuildingArea', data=df, palette=colors)
plt.ylim(0, 7000) #устанавливаем максимальное значение
plt.show()
sns.boxplot(x='Type', y='BuildingArea', data=df, palette=colors)
plt.ylim(0, 750)
plt.xlabel('Type') #устанавливаем максимальное значение
plt.ylabel('Building Area (м. кв)') #устанавливаем максимальное значение
plt.title('Зависимость площади от типа')
plt.show()

pie_df = df['Type'].value_counts().reset_index()
plt.pie(
    pie_df['count'],
    labels= pie_df['Type'],
    colors = ['yellow', 'skyblue', 'pink'],
    autopct='%1.1f%%'
)

plt.title('Типы зданий')
plt.show()